# Generated by Django 6.0.2 on 2026-05-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Bedroom', 'Bedroom'), ('Living Room', 'Living Room'), ('Office', 'Office'), ('Kitchen', 'Kitchen')], max_length=50)),
                ('position', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center'), ('Corner', 'Corner'), ('Front', 'Front'), ('Back', 'Back'), ('Wall', 'Wall')], default='Center', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='furniture/')),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
