# Generated by Django 6.0.2 on 2026-05-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='image',
            field=models.URLField(),
        ),
    ]
