# Generated by Django 6.0.2 on 2026-05-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('discount', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('rating_count', models.CharField(max_length=100)),
            ],
        ),
    ]
