# Generated by Django 6.0.2 on 2026-05-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groceryproduct',
            table='Groceries_grocery',
        ),
    ]
