# Generated by Django 6.0.2 on 2026-05-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groceries', '0002_alter_groceryproduct_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryproduct',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
