# Generated by Django 6.0.2 on 2026-05-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='loginditails',
            new_name='LoginDetail',
        ),
    ]
