# Generated by Django 6.0.2 on 2026-05-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_loginditails_logindetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetail',
            name='password',
        ),
        migrations.AddField(
            model_name='logindetail',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
