# Generated by Django 6.0.2 on 2026-05-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_logindetail_password_logindetail_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindetail',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
