# Generated by Django 6.0.2 on 2026-05-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_logindetail_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetail',
            name='password',
        ),
    ]
