# Generated by Django 6.0.2 on 2026-05-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_delete_logindetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LoginDetail',
        ),
    ]
