# Generated by Django 6.0.2 on 2026-05-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_user_logindetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindetail',
            name='mobile',
        ),
        migrations.AddField(
            model_name='logindetail',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
