# Generated by Django 6.0.2 on 2026-05-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FashionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('skin_type', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
