# Generated by Django 6.0.2 on 2026-05-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionproduct',
            name='gender',
            field=models.CharField(default='men', max_length=100),
        ),
    ]
