# Generated by Django 6.0.2 on 2026-05-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_fashionproduct_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionproduct',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
