# Generated by Django 6.0.2 on 2026-06-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=1000)),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('rating', models.FloatField()),
                ('skin_type', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('shade', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
